site_name: lernOS AI Guide
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/en

nav:
    - Welcome: index.md
    - Basics:
      - AI & Machine Learning: 1-2-ai-machine-learning.md
      - Neural networks: 1-3-neuronal-networks.md
      - Machine vs. human learning: 1-4-machine-vs-human-learning.md
      - AI application areas: 1-5-ai-application-areas.md
      - AI models: 1-6-ai-models.md
      - AI tools & services: 1-7-ai-tools-services.md
      - Create prompts: 1-8-prompts-erstellen.md
      - AI & society: 1-9-ai-and-society.md
      - Further information: 1-10-further-information.md
    - Learning path:
      - Introduction: 2-0-learning-pathway.md
      - Preparation & Get together (Kata 0): 2-1-kata-0.md
      - Create awareness (Kata 1): 2-2-kata-1.md
      - Getting started with the AI (Kata 2): 2-3-kata-2.md
      - AI as a dialogue partner (Kata 3): 2-4-kata-3.md
      - Reflection on learning outcomes (Kata 4): 2-5-kata-4.md
      - Fields of application in your own workplace (Kata 5): 2-6-kata-5.md
      - Consolidation of your learning objective (Kata 6): 2-7-kata-6.md
      - Collaboration with AI (Kata 7): 2-8-kata-7.md
      - Reflection on learning outcomes (Kata 8): 2-9-kata-8.md
      -  AI as dreamer, hallucinator or liar (Kata 9): 2-10-kata-9.md
      - Confident prompting part 1 (Kata 10): 2-11-kata-10.md
      - Confident prompting part 2 (Kata 11): 2-11-kata-11.md
      - Review and Lessons Learned (Kata 12): 2-12-kata-12.md
    - Appendix: 3-0-appendix.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-ai/blob/master/de/lernos-ai-guide.pdf
      - Word-Version: https://github.com/cogneon/lernos-ai/blob/master/de/lernos-ai-guide.docx
      - HTML-Version: https://github.com/cogneon/lernos-ai/blob/master/de/lernos-ai-guide.html
      - E-Book (epub): https://github.com/cogneon/lernos-ai/blob/master/de/lernos-ai-guide.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-ai/blob/master/de/lernos-ai-guide.mobi
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: en
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate 

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-ai'
repo_url: 'https://github.com/cogneon/lernos-ai'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    analytics:
       provider: custom
    alternate:
         - name: German
           link: https://ai.lernos.org/de
           lang: de

plugins:
  - search