name: lernOS Produktionskette

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      # Repository auschecken, damit Workflow es nutzen kann
      - uses: actions/checkout@v3
      
      # Delete Old Versions
      # de
      - run: rm -rf ./de/${{ github.event.repository.name }}-guide.*
      - run: rm -rf ./docs/de/*
      # en
      - run: rm -rf ./en/${{ github.event.repository.name }}-guide.*
      - run: rm -rf ./docs/en/*

      # Create Chapter List
      - name: Create Chapter Lists
        id: chapter_list
        run: echo "chapters=$(printf '%s ' ./de/src/[0-9]*.md)" >> "$GITHUB_OUTPUT"
      
      # Create Microsoft Word Version (docx)
      - uses: docker://pandoc/core
        with:
          args: >-
            ./de/metadata.yaml
            --standalone
            --resource-path=./de/src
            --number-sections
            --toc
            --toc-depth=2
            -V lang=de-de
            --output=./de/${{ github.event.repository.name }}-guide.docx
            ./de/src/index.md ${{ steps.chapter_list.outputs.chapters-de }}

      # Create HTML Version (html)
      - uses: docker://pandoc/core
        with:
          args: >-
            ./de/metadata.yaml
            --standalone
            --resource-path=./de/src
            --number-sections
            --toc
            --toc-depth=2
            -V lang=de-de
            --output=./de/${{ github.event.repository.name }}-guide.html
            ./de/src/index.md ${{ steps.chapter_list.outputs.chapters-de }}

      # Create eBook Version (epub)
      - uses: docker://pandoc/core
        with:
          args: >-
            ./de/metadata.yaml
            --standalone
            --resource-path=./de/src
            --number-sections
            --toc
            --toc-depth=2
            -V lang=de-de
            --output=./de/${{ github.event.repository.name }}-guide.epub
            ./de/src/index.md ${{ steps.chapter_list.outputs.chapters-de }}

      # Create PDF Version (pdf)
      # de
      - uses: docker://pandoc/extra
        with:
          args: >-
            ./de/metadata.yaml
            --standalone
            --resource-path=./de/src
            --number-sections
            --toc
            --toc-depth=2
            -V lang=de-de
            --template /.pandoc/templates/eisvogel.latex
            --output=./de/${{ github.event.repository.name }}-guide.pdf
            ./de/src/index.md ${{ steps.chapter_list.outputs.chapters-de }}

      # en
      - uses: docker://pandoc/extra
        with:
          args: >-
            ./en/metadata.yaml
            --standalone
            --resource-path=./en/src
            --number-sections
            --toc
            --toc-depth=2
            -V lang=en-GB 
            --template /.pandoc/templates/eisvogel.latex
            --output=./en/${{ github.event.repository.name }}-guide.pdf
            ./en/src/index.md ${{ steps.chapter_list.outputs.chapters-en }}


      # WEBVERSIONEN
      # Create Web Version de (mkdocs)
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs build -f ./de/mkdocs.yml

      # Create Web Version en (mkdocs)
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs build -f ./en/mkdocs.yml


      # Geänderte Datein zurück ins Repository committen
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Erzeugt von automatischer lernOS Produktionskette
